### ISSUE TITLE
[Bug] Fallback hook will always pick up the current context

### ISSUE THREAD

**Issue by TimDiekmann** [hashintel/hash#1091]
### Describe the bug

When a fallback hook is set, the context (if not another hook is set) will run the hook, so the output will be

```
invalid input parameter
├╴test.rs:10:18
╰╴Frame { location: Location { file: "test.rs", line: 10, col: 18 }, context: Kind(InvalidInput) }
```

while the last printed attachment is emitted by the fallback with the context frame

### To reproduce

```Rust
use std::io::{Error, ErrorKind};

use error_stack::Report;

fn main() {
    Report::install_debug_hook_fallback(|frame, ctx| {
        ctx.push_body(format!("{frame:?}"));
    });

    let report = Report::new(Error::from(ErrorKind::InvalidInput));

    println!("{report:?}");
}
```

### Expected behavior

The context should not be appended as an attachment as well, so the output should be

```
invalid input parameter
╰╴test.rs:10:18
```

### Rust compiler

1.63 and 1.65.0-nightly (2022-08-26)

### Host

aarch64-apple-darwin

### Target

aarch64-apple-darwin

### Version

latest git revision (cf5d85ea)

### Features

all

**Comment by TimDiekmann** [comment]
I wonder how we could solve this. I see three possible solutions:
1. Don't run any hooks on `Context` frames
1. Not run the fallback on `Context` frames, only on `Attachment` frames. This may be confusing
1. Remove the fallback hook

**Comment by indietyp** [comment]
I'd go with (3), I think the hook system by itself is a lot more complete and versatile than it was when we started.

Especially with the integration of the Provider api on nightly.

I don't really see a remaining use-case for fallbacks.
