### ISSUE TITLE
`Display` implementation only shows latest context

### ISSUE THREAD

**Issue by FlixCoder** [hashintel/hash#1595]
### Describe the bug

Hi,
First of all, thanks for the great work, `error-stack` has helped me for proper error handling with attachable information like whether an error is retryable.

To the point: I am trying to output errors with a changed context in them, but it only prints out the latest context.

### To reproduce

```Rust
// 1. I have an error of type ErrorA in a result.
// 2. I call `result.into_report().change_context(ErrorB::Something)?`.
// 3. (I attach information like `result.attach(Retryable::Yes)`.)
// 4. (I match on the report in the result and call `err.downcast_ref::<Retryable>`.)
// 5. I print the error, but it only gives `ErrorB::Something`

use error_stack::{bail, Report, ResultExt};
use thiserror::Error;

fn main() {
    if let Err(err) = changing_function() {
        println!("Error: {err}");
    }
    println!("Done");
}

fn changing_function() -> Result<(), Report<ErrorB>> {
    erroring_function().change_context(ErrorB::Variant)?;
    Ok(())
}

fn erroring_function() -> Result<(), Report<ErrorA>> {
    bail!(ErrorA::Variant);
}

#[derive(Debug, Error)]
enum ErrorA {
    #[error("Error A")]
    Variant,
}

#[derive(Debug, Error)]
enum ErrorB {
    #[error("Error B")]
    Variant,
}
```

### Expected behavior

From the implementation of `Display`, it looks like it iterates over the frames and prints out all. When I manually iterate over the frames and do a `dbg!` on them, I can also see there is another frame with a context that includes `ErrorA`. However, while printing, it is gone. I assume it somehow gets considered as attachment, even though it should not be right?

### Rust compiler

rustc 1.65.0 (897e37553 2022-11-02)

### Host

x86_64-unknown-linux-gnu

### Target

stable-x86_64-unknown-linux-gnu

### Version

v0.2.4

### Features

default

**Comment by TimDiekmann** [comment]
Hi @FlixCoder and thanks for your issue, glad you like `error-stack`! 🙂 

The behavior you described is expected behavior. To `Display` an error, `error-stack` uses the same behavior as `anyhow`:
- `Display` only prints the latest context/error: `println!("Error: {err}")` will print `"Error: Error B"`
- extended `Display` prints all contexts:  `println!("Error: {err:?}")` will print `"Error: Error B: Error A"`
- `Debug` prints the full stack of errors:
   ```
    Error: Error B
    ├╴ main.rs:18:25
    │
    ╰─▶ Error A
        ├╴ main.rs:23:5
        ╰╴ backtrace with 15 frames (1)

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    backtrace no. 1
    [redacted]
   ```

Does this solve your issue?

---

> I attach information like `result.attach(Retryable::Yes)`

That's a really cool way to utilize attachments! 🎉

**Comment by FlixCoder** [comment]
Oh I didn't know there is extended Display wow :D Ok that solves it yeah, thanks!

**Comment by TheAlgorythm** [comment]
It would be cool if there were a a pretty printed version of the the extended version. In contrast to `Debug` it shouldn't include the locations and backtrace as it is to much Information for an user.

The example from the README could look like this:
```
could not parse configuration file
├╴could not read file "test.txt"
├╴1 additional opaque attachment
│
╰─▶ No such file or directory (os error 2)
```
