### ISSUE TITLE
'Could not find any Visual Studio installation to use'

### ISSUE THREAD

**Issue by geertdoornbos** [hashintel/hash#1768]
### Describe the bug

During step 3 of the [Getting Started](https://github.com/hashintel/hash/tree/main/packages/hash) process,
> yarn install

did not complete successfully. 

Logs:
...
node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@8.3.0
gyp info using node@18.12.1 | win32 | x64
gyp info find Python using Python version 3.10.2 found at "C:\Users\geert\AppData\Local\Programs\Python\Python310\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS running in VS Command Prompt, installation path is:
gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Professional"
gyp ERR! find VS - will only use this version
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Professional"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\hash\hash\node_modules\re2\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\hash\hash\node_modules\re2\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\hash\hash\node_modules\re2\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\hash\hash\node_modules\re2\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\hash\hash\node_modules\re2\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\hash\hash\node_modules\re2\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\hash\hash\node_modules\re2\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\hash\\hash\\node_modules\\re2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\hash\hash\node_modules\re2
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v8.3.0
gyp ERR! not ok
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

### To reproduce

Follow 'Getting started' procedure.

### Operating system

Windows 11

### Additional context

- I validated dependency versions.
- I do have workload "Desktop development with C++" installed.
- I tried to set 'msvs_version', but got the same results.

node-gyp@8.3.0 is being used. Version [node-gyp@9.1.0](https://github.com/nodejs/node-gyp/pull/2565) seems to have better support for Windows 11 SDK? 
How to update node-gyp version?

**Comment by geertdoornbos** [comment]
By changing /packages/hash/frontend/package.json dependency:

> "url-regex-safe": "2.0.2",

to 

> "url-regex-safe": "3.0.0",

url-regex-safe@3.0.0 uses re2@1.18.0, which uses node-gyp@9.3.0, which has the update for finding Visual Studio 2022.

Now the build succeeds, but running the next step in the Getting Started process ('yarn external-services up') shows more errors... so next attempt; run on WSL.

**Comment by nonparibus** [comment]
Follow-on issue running in WSL: https://github.com/hashintel/hash/issues/1789
