### ISSUE TITLE
Can't see crash output when using solarized-dark color scheme

### ISSUE THREAD

**Issue by dpc** [hashintel/hash#1782]
### Describe the bug

![Screenshot from 2023-01-07 23-48-27](https://user-images.githubusercontent.com/9209/211185860-22b210dd-f924-4447-988f-e05c9a4c109c.png)

I use solarized-dark color scheme in my terminals and noticed after upgrading that I can not see some parts of the output (until I highlight it).

### Expected behavior

Would be better if I was able to see colors. I think I've seen that color output is behind an optional cargo feature, so I'm going to try disabling them, and that's good enough workaround for me, I think.

BTW. Recently `clap` has made a decision to abandon colors and rely only on underline, bold font, etc. to make the output readable. 

The reasoning was that not only it's hard to find color scheme that works for everyone, but also - businesses and teams have sometimes their own branding etc. and error colors might get in a way.

**Comment by indietyp** [comment]
Hey! Just as a side-note we also support the NO_COLOR environment variable. Setting NO_COLOR=1 will disable color output for error-stack.

**Comment by TimDiekmann** [comment]
With #1800 it's now possible to choose the `ColorMode` and it will be available with error-stack 0.3, which is planned to be released today (maybe tomorrow, but we're targeting today).
