### ISSUE TITLE
Unable to build hash

### ISSUE THREAD

**Issue by geertdoornbos** [hashintel/hash#1789]
### Describe the bug

I tried to build Hash from scratch using WSL, following the [Getting Started](https://github.com/hashintel/hash/tree/main/packages/hash) steps.

### To reproduce

Using Ubuntu 20.04.5 LTS (up to date)

Checked versions of Git, Node, Yarn, Docker

- creating folder 'hashintel'
- git clone https://github.com/hashintel/hash.git
- cd into folder 'hash'
- yarn install

### Expected behavior

Expected succesful result, but install ends with:

>[4/4] Building fresh packages...
[-/18] ⠠ waiting...
[-/18] ⠠ waiting...
[14/18] ⠠ @sentry/cli
[-/18] ⠐ waiting...
error /mnt/c/hashintel/hash/node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node ./scripts/install.js
Arguments:
Directory: /mnt/c/hashintel/hash/node_modules/@sentry/cli
Output:
info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.74.6/sentry-cli-Linux-x86_64

### Operating system

Ubuntu 20.04.5 LTS (up to date)

**Comment by nonparibus** [comment]
Hi Geert, thanks for your patience as we look into this.

It looks like `@sentry/nextjs` which we use imports `@sentry/webpack-plugin`, which in turn relies on `@sentry/cli@^1.74.6`. This contains an issue (https://github.com/getsentry/sentry-cli/pull/1344) which was patched in later versions, but the downstream dependents have not yet been updated. There's an open issue (https://github.com/getsentry/sentry-webpack-plugin/pull/383) for this.

Removing Sentry won't be trivial for us, but we do have Windows users running the app successfully using WSL. I'll find our more about what their setups look like and post here/update the docs.

**Comment by geertdoornbos** [comment]
Hi David, thanks for this find about sentry; fully understandable. Unfortunately, a 'it works on my machine' scenario. I'll retry in near future. In the mean time; trying to get a better understanding of the BP. 👍
