### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by indietyp** [hashintel/hash#1869]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Pending Approval

These branches will be created by Renovate only once you click their checkbox below.

 - [ ] Update dependency rust to v2023-01-16

## Detected dependencies

<details><summary>regex</summary>
<blockquote>

<details><summary>libs/deer/rust-toolchain.toml</summary>

 - `rust 2022-11-14`

</details>

<details><summary>packages/graph/rust-toolchain.toml</summary>

 - `rust 2023-01-03`

</details>

<details><summary>packages/libs/error-stack/rust-toolchain.toml</summary>

 - `rust 2022-12-09`

</details>

<details><summary>packages/libs/error-stack/README.md</summary>

 - `rust 2022--12--09`

</details>

<details><summary>packages/libs/error-stack/macros/README.md</summary>

 - `rust 2022--11--14`

</details>

<details><summary>packages/libs/error-stack/src/lib.rs</summary>

 - `rust 2022--12--09`

</details>

</blockquote>
</details>

**Comment by nonparibus** [comment]
See https://github.com/hashintel/hash/issues/1481 instead.
