### ISSUE TITLE
Automatic conversion from errors to error stack?

### ISSUE THREAD

**Issue by bjchambers** [hashintel/hash#1981]
### Related Problem

When using a library (such as Apache Arrow) that returns it's own non-error stack error types, I sometimes find there is a lot of boilerplate for handling this. For instance, running three "kernels" from arrow may become:

```
arrow::method1(...).into_report().change_context(Error::Internal)?;
arrow::method2(...).into_report().change_context(Error::Internal)?;
arrow::method3(...).into_report().change_context(Error::Internal)?;
```

I sometimes wish there was a way to say "allow an automatic conversion from `Result<T, arrow::error::Error>` to `error_stack::Result<T, C>` for my error type.

### Proposed Solution

I believe such an automatic conversion could be handled by implementing `From` for arbitrary error types and contexts. Something like:

```
trait ForError<E> {
  fn for_error(source: &E) -> Self;
}

impl<C> From<E> for error_stack::Report<C> where C: ForError<E> {
  #[track_caller]
  fn from(source: E) -> Self {
    let context = source.for_error();
    source.into_report().change_context(context)
  }
}
```

Then, I believe that I could do:

```
enum MyError {
  ...,
  ArrowError,
}

impl ForError<arrow::error::Error> for MyError {
  fn for_error(_: &arrow::error::Error) -> Self {
    Self
  }
}
```

### Alternatives

I've considered (and at times do) break out the methods that all have the same type of error into a helper that returns `error_context::Result<T, arrow::error::Error>`. This lets me rely on the existing automatic call to `.into_report()`, and then assign the context "outside". This breaks down when there is a step in between some of the Arrow calls that needs to return a different kind of error, since  there is no longer a compatible error type.

**Comment by TimDiekmann** [comment]
Hi, @bjchambers, and thanks for filing the issue.

I definitely see the issue that this get’s verbose quickly, however, if a function returns the same context all the time with the exact same attachments it suggests that either the initial error is the same all the time (so you could use `Report<ArrowError>` instead) or you’re dropping error information. The design of `error-stack` intentionally didn’t use the `From` trait and introducing just another trait to bypass this is not really the solution.

**Comment by TimDiekmann** [comment]
Worth mentioning that we're [going to remove `IntoReport`](https://github.com/hashintel/hash/pulls), so the `into_report()` call is not needed in the future.
