### ISSUE TITLE
Mapbox service calls fail in cloud-executed simulation runs

### ISSUE THREAD

**Issue by ghabs** [hashintel/hash#20]
Calls to external services are currently disabled in cloud experiment runs, so [Mapbox API calls](https://docs.hash.ai/core/creating-simulations/agent-messages/built-in-message-handlers#navigation-with-mapbox) that work in hCore don't currently work when running simulations on the HASH simulation cloud.

**Comment by nonparibus** [comment]
Relates to old hCloud infra.
