### ISSUE TITLE
error[E0554]: `#![feature]` may not be used on the stable release channel 

### ISSUE THREAD

**Issue by Keon6** [hashintel/hash#2404]
### Describe the bug

Running into this issue when `cargo build` is compiling nano v0.0.0 and as a result when `cargo run` despite that I've already activated nightly toolchain.

Not sure what's going on, I tried all the tricks in the book including rustup default nightly. Still not working....

### To reproduce

1. run `cargo build` under engine directory
2. run `cargo run` under same directory

### Expected behavior

I guess it's just supposed to run?

### Rust compiler

1.68.2 

### Host

aarch64-apple-darwin

### Target

nightly-2022-08-08-aarch64-apple-darwin

### Version

3.8.10

**Comment by TimDiekmann** [comment]
Hi @Keon6 and thanks for the issue.

> **Rust compiler**
> 1.68.2

This does not look like a nightly compiler. Could you run `rustup show` inside of the engine directory and post the output, please?

**Comment by Keon6** [comment]
Default host: aarch64-apple-darwin
rustup home:  /Users/keonshikkim/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2022-08-08-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)

active toolchain
----------------

nightly-aarch64-apple-darwin (overridden by '/Users/keonshikkim/VisualStudio/hash-test-drive/apps/engine/rust-toolchain.toml')
rustc 1.70.0-nightly (9df3a39fb 2023-04-11)

**Comment by Keon6** [comment]
idk why rustc and rustup show show me different versions

**Comment by TimDiekmann** [comment]
This is interesting, as this is the output when I run `rustup show` in the engine folder (which is actually the expected output)

> active toolchain
> ----------------
>
> nightly-2022-08-08-aarch64-apple-darwin (overridden by '/Users/[...]/hash/apps/engine/rust-toolchain.toml')
> rustc 1.65.0-nightly (d394408fb 2022-08-07)

I assume you don't have changed anything?
Could you try running with specifying the toolchain manually?
```sh
$ cargo +nightly-2022-08-08 build
```

**Comment by Keon6** [comment]
that's the weird thing - I can't run anything `cargo +nightly <enter command>`

error: no such command: `+nightly-2022-08-08`

        Cargo does not handle `+toolchain` directives.
        Did you mean to invoke `cargo` through `rustup` instead?

**Comment by TimDiekmann** [comment]
That's indeed interesting. Could you post the output of `which cargo` and `which rustup`? How did you install Rust? We strongly recommend using https://rustup.rs and not via a package manager like Homebrew. In many cases, this causes issues when trying to compile Rust crates.

**Comment by TimDiekmann** [comment]
My suggestion is to altogether remove `Rust` (`rustc`, `rustup`, `cargo`) from your system (varify this with `which <command>`) and use `rustup.rs` to install Rust from scratch.

**Comment by Keon6** [comment]
> That's indeed interesting. Could you post the output of `which cargo` and `which rustup`? How did you install Rust? We strongly recommend using https://rustup.rs and not via a package manager like Homebrew. In many cases, this causes issues when trying to compile Rust crates.


        $ which cargo
        /opt/homebrew/bin/cargo
        $ which rustup
        /Users/keonshikkim/.cargo/bin/rustup

Rust was installed using directions from rust lang homepage.

**Comment by Keon6** [comment]
> My suggestion is to altogether remove Rust (rustc, rustup, cargo) from your system (verify this with which <command>) and use rustup.rs to install Rust from scratch.

I've already tried this. It's still an issue.

**Comment by Keon6** [comment]
Nvm, this is actually resolved.

For others make sure you don've hve other versions of rust isntalled using other installers. I had a conflicting version with homebrew
