### ISSUE TITLE
Issue while bootstrapping `yarn create block-app`

### ISSUE THREAD

**Issue by MatteoGauthier** [hashintel/hash#247]
```
error /Users/matteogauthier/dev/blocks/user-profile/node_modules/mock-block-dock: Command failed.
Exit code: 127
Command: yarn build
Arguments: 
Directory: /Users/matteogauthier/dev/blocks/user-profile/node_modules/mock-block-dock
Output:
yarn run v1.22.17
$ yarn clean; yarn build:cjs; yarn build:esm
$ rimraf ./dist/
/bin/sh: rimraf: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ tsc --p tsconfig.build.json --module commonjs --outDir dist/cjs 
/bin/sh: tsc: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ tsc --p tsconfig.build.json
/bin/sh: tsc: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documenta
```

the postinstall seems to use `tsc` which is not installed locally

**Comment by kachkaev** [comment]
👋 @MatteoGauthier thanks for reporting this issue! Sorry for a broken package we’ve accidentally published. I hope we’ll fix it in the next day or so – let’s track the issue here: https://github.com/blockprotocol/blockprotocol/issues/161

🙌

**Comment by MatteoGauthier** [comment]
No problem 😃

**Comment by kachkaev** [comment]
https://github.com/blockprotocol/blockprotocol/issues/161 and https://github.com/blockprotocol/blockprotocol/issues/162 have been resolved. We have also [added smoke tests](https://github.com/blockprotocol/blockprotocol/pull/178) for the packages we publish to avoid similar errors in the future. 

Thanks again for reporting this issue and let us know if you have any more thoughts! 🙌
