### ISSUE TITLE
hCloud Error when running experiment for Python Model - Using Pandas library

### ISSUE THREAD

**Issue by AlABarazi** [hashintel/hash#2471]
### Describe the bug

Whenever I run a Python model as an experiment which import pandas library  , some of the agents disappear from the model.  However, the same model run without problem otherwise (normal run) 

For example in the simulation https://core.hash.ai/@alaabarazi/actorexperiment/main a problem occures when the tabular data (csv) is processed by the behavior "init_bim_read_tasks.py" which  import  pandas, datatime and numpy for this propose. The code read the data from csv file and assign the values to the relevant agent.

Attacehd photos (experiment) is the output of the experiment run when pandas is imported and it shows that the external walls are not showing, and the values from csv file are not added to the agents. (pandas did not work as it should)
![Experiment](https://user-images.githubusercontent.com/7549404/233656198-94c4e90d-f572-43e4-adeb-6c69d1c7d06e.png)

Attached photo (normal) is the output of the normal run when pandas is  imported and it shows that the external walls are  there, and the values from  csv file are  added to the agents

![normal_run](https://user-images.githubusercontent.com/7549404/233656368-faa3e4ab-4760-40b3-8038-b94f48fa8697.png)

### To reproduce

go to https://core.hash.ai/@alaabarazi/actorexperiment/main
run the model normally 
run the model as an experiment 
compare both (normal run vs experiment run )

### Expected behavior

Experiment run should match normal run

### Project URL

https://core.hash.ai/@alaabarazi/actorexperiment/main

### Device

2,6 GHz 6-Core Intel Core i7

### Operating system

13.3.1 (22E261)

### Browser

Version 112.0.5615.121 (Official Build) (x86_64)

**Comment by nonparibus** [comment]
Duplicates existing ticket https://github.com/hashintel/hash/issues/2438 - the original ticket will be updated to include this one as additional context.
