### ISSUE TITLE
`IntoReport` is deprecated, but `ReportExt` that replaces it is not in `error-stack`

### ISSUE THREAD

**Issue by matiu2** [hashintel/hash#3087]
### Describe the bug

When I upgraded to 0.4.0 or error_stack I got this error_message:

```
warning: use of deprecated trait `error_stack::IntoReport`: Use `ReportExt` or `From` via `Result::map_err(Report::from)` instead
```

I couldn't find `ResultExt` anywhere. In the end I had to download the whole `hash` mono-repo and grep it.

It is in `deer` which I don't want to import into my project:

```
libs/deer/src/error.rs
465:pub trait ReportExt<C: Context> {
469:impl<C: Context> ReportExt<C> for Report<C> {
```

### To reproduce

```Rust
Just make a new rust project that uses error-stack 0.4.0 and try to use IntoReport.
```

### Expected behavior

It'd be nice to have the replacement trait inside of error-stack itself, and not need to import `deer`.

### Rust compiler

rustc 1.72.0 (5680fa18f 2023-08-23)

### Host

host: x86_64-unknown-linux-gnu

### Target

x86_64-unknown-linux-gnu

### Version

v0.4.0

### Features

default

**Comment by TimDiekmann** [comment]
Hi, @matiu2.

I don't really can follow your issue, the [`ResultExt` is available in `error-stack`](https://docs.rs/error-stack/0.4.0/error_stack/trait.ResultExt.html). Could you provide a code example that does not work?

All you have to do is to remove the `into_report()` call and import `error_stack::ResultExt`. In some rare cases where the error type is not available you need to specify it, e.g. by `.map_err(Report::new)` but in most cases this is not needed.

**Comment by TimDiekmann** [comment]
I just noticed, that the deprecation warning says `ReportExt` instead of `ResultExt`. Btw, you have written `ResultExt` as well. I opened a PR and will a new version to avoid further confusion.

Thanks for reporting the issue!
