### ISSUE TITLE
H-3831: Email form in footer throws "Invalid email" for valid emails

### ISSUE THREAD

**Issue by annapowellsmith** [hashintel/hash#5938]
### Describe the bug

Attempting to submit an email address in the footer form produces "Invalid email", for valid emails. 

<img width="932" alt="Screenshot 2024-12-17 at 11 43 16" src="https://github.com/user-attachments/assets/878bcc61-c564-4095-8a53-9dbbc9af0063" />

This appears to be a frontend bug: Zod expects `tags` to be an array of strings, but `tags` is undefined. 

<img width="399" alt="Screenshot 2024-12-17 at 11 47 39" src="https://github.com/user-attachments/assets/20ad1ab8-8535-4f7b-a3dc-b25faf4af1a7" />

### To reproduce

1. Visit any page on the website
2. Scroll down to the footer signup form 
3. Attempt to submit a valid email
4. See "Invalid email"
5. Feel sad 

### Browser

Tested in Chrome and Safari

**Comment by vilkinsons** [comment]
Hi @annapowellsmith Thanks for flagging; sorry about this. Taking a look now!

**Comment by vilkinsons** [comment]
Hi @annapowellsmith This should now have been fixed. Sorry about that! You should be able to create an account at [app.hash.ai/signup](https://app.hash.ai/signup) if you haven't already.

**Comment by annapowellsmith** [comment]
Yup, works now! 👍
