### ISSUE TITLE
error_stack errors improperly parsed by rust-mode on emacs

### ISSUE THREAD

**Issue by wildwestrom** [hashintel/hash#811]
This is related to https://github.com/rust-lang/rust-mode/issues/452.
I won't repost all the information from there.

Since trying to make rust-mode also parse this particular type of error seems a bit cumbersome, I think it may make sense to add a `.dir-locals.el` file that somebody can drop into their project.

**Comment by wildwestrom** [comment]
```emacs-lisp
  (setq error_stack-regexps
    '("\\(?:at\\|',\\) \\(\\([^:\s]+\\):\\([0-9]+\\)\\)"
      2 3 nil nil 1))
  (setf (cdr (assoc 'cargo compilation-error-regexp-alist-alist))
        error_stack-regexps)
```
Here's my current workaround. I just need to figure out how to make this work locally only.
Of course, if it's not a problem for @rust-lang to add this to [rust-mode](https://github.com/rust-lang/rust-mode) then I won't have to consider this as an option.

**Comment by wildwestrom** [comment]
> Would you like to open a PR for this?
Absolutely!
I'm thinking that since there is no way to make `compilation-error-regexp-alist-alist` a local variable, then I'll have to edit the list itself.
Maybe this can just be somewhere in documentation. What do you think?

**Comment by TimDiekmann** [comment]
I never used emacs so I'm probably the wrong one to ask if/how this is possible. Adding this to the README.md sounds reasonable I think!
