### ISSUE TITLE
`error-stack` does not compile on newest nightly

### ISSUE THREAD

**Issue by indietyp** [hashintel/hash#873]
Due to https://github.com/rust-lang/rust/issues/96024#issuecomment-1179168910 (https://github.com/rust-lang/rust/pull/98912) the following no longer compiles:

https://github.com/hashintel/hash/blob/b850b02c3dbf1bd2cbbb404baa6ea1d581389cde/packages/libs/error-stack/src/report.rs#L235-L253

**Comment by indietyp** [comment]
It would need to be `core::any::request_ref::<Backtrace>` instead.

**Comment by indietyp** [comment]
We could adopt the new behavior or use https://github.com/dtolnay/rustversion for some conditional compilation to allow for both. This would mean we would need to add a new dependency to error-stack (not ideal)

**Comment by TimDiekmann** [comment]
Fixed in dev, will be available with `0.2.0`. Thanks for reporting and fixing it!
