### ISSUE TITLE
[BUG] error-stack not building on latest nightly

### ISSUE THREAD

**Issue by jquesada2016** [hashintel/hash#957]
**Describe the bug**  
Trying to build on latest nightly fails with the following error:

```
error[E0599]: no method named `backtrace` found for reference `&'a C` in the current scope
   --> /home/joseprogdp/.cargo/registry/src/github.com-1ecc6299db9ec823/error-stack-0.1.1/src/context.rs:108:39
    |
108 |         if let Some(backtrace) = self.backtrace() {
    |                                       ^^^^^^^^^ method not found in `&'a C`
```

**To reproduce**  
Update to the latest nightly toolchain with `rustup update` or switch to it with `rustup default nightly`. After this, create a new cargo project and add `error-stack` as a dependency. Run `cargo r` or `carbo b` and observe the error.

**Expected behavior**  
I expected `error-stack` to build.

**Desktop (please complete the following information):**

- OS: Windows 11
- rustc: 1.65.0-nightly (9c20b2a8c 2022-08-17)
- target: wasm32-unknown-unknown
- Version: latest
- Features: default

**Comment by jquesada2016** [comment]
I accidentally lied about the `OS` I'm using. I'm using Ubuntu through WSL2 on Windows 11.

**Comment by TimDiekmann** [comment]
We will file a new release pretty soon after https://github.com/hashintel/hash/pull/794 was merged, sorry for the inconvenience 🙁
